import { ITestimonialData } from '../_interface/testimonial'

export const cardData: ITestimonialData[] = [
  {
    id: 1,
    name: 'Bipina Bajracharya',
    position: 'Project Engineer in Dolidar',
    desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
    img: '/home/stud.jpg',
  },
  {
    id: 2,
    name: 'Kusma Rai',
    position: 'George Washington University',
    desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
    img: '/home/stud.jpg',
  },
  {
    id: 3,
    name: 'Bipina Bajracharya',
    position: 'Project Engineer in Dolidar',
    desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
    img: '/home/stud.jpg',
  },
  {
    id: 4,
    name: 'Kusma Rai',
    position: 'George Washington University',
    desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
    img: '/home/stud.jpg',
  },
  {
    id: 5,
    name: 'Bipina Bajracharya',
    position: 'Project Engineer in Dolidar',
    desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
    img: '/home/stud.jpg',
  },
  // {
  //   id: 6,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 7,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 8,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 9,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 10,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 11,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 12,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 13,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 14,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 15,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 16,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 17,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 18,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 19,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 20,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 21,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 22,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 23,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 24,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 25,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 26,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 27,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 28,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 29,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 30,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
  // {
  //   id: 31,
  //   name: 'Bipina Bajracharya',
  //   position: 'Project Engineer in Dolidar',
  //   desc: 'After completing my SLC from Shree Champawati Secondary School,  I joined at Pawan Prakriti Secondary School for class 11.  The teachers were very kind and helpful who  taught me how to be  laborious and focus on stud.',
  //   img: '/home/stud.jpg',
  // },
]
